import scripts.libAnt.profiles.profile as profiles
import scripts.libAnt.profiles.power_profile as power_profile
import scripts.libAnt.profiles.speed_profile as speed_profile
import scripts.libAnt.profiles.cadence_profile as cadence_profile
import scripts.libAnt.profiles.speed_cadence_profile as speed_cadence_profile
import scripts.libAnt.profiles.heartrate_profile as heartrate_profile
import scripts.libAnt.profiles.fitness_equipment_profile as fitness_equipment_profile

# DEVICE CONSTANTS
WAHOO_KICKR_SNAP_STRING = "Wahoo Kickr Snap"
WAHOO_KICKR_SNAP = [15887, 45054]
WAHOO_CADENCE_SENSOR_STRING = "Wahoo Cadence Sensor"
WAHOO_CADENCE_SENSOR = 54013
WAHOO_SPEED_SENSOR_STRING = "Wahoo Speed Sensor"
WAHOO_SPEED_SENSOR = 1458

DeviceNumber2Name = {
    WAHOO_KICKR_SNAP[0]: WAHOO_KICKR_SNAP_STRING,
    WAHOO_KICKR_SNAP[1]: WAHOO_KICKR_SNAP_STRING,
    WAHOO_SPEED_SENSOR: WAHOO_SPEED_SENSOR_STRING,
    WAHOO_CADENCE_SENSOR: WAHOO_CADENCE_SENSOR_STRING
}


# PROFILE CONSTANTS
FITNESS_EQUIPMENT_PROFILE_STRING = "Fitness Equipment"
FITNESS_EQUIPMENT_PROFILE = profiles.FITNESS_EQUIPMENT_PROFILE

POWER_PROFILE_STRING = "Power"
POWER_PROFILE = profiles.POWER_PROFILE

SPEED_PROFILE_STRING = "Speed"
SPEED_PROFILE = profiles.SPEED_PROFILE

CADENCE_PROFILE_STRING = "Cadence"
CADENCE_PROFILE = profiles.CADENCE_PROFILE

SPEED_CADENCE_PROFILE_STRING = "Speed and Cadence"
SPEED_CADENCE_PROFILE = profiles.SPEED_CADENCE_PROFILE

ProfileName2Number = {
    FITNESS_EQUIPMENT_PROFILE_STRING: FITNESS_EQUIPMENT_PROFILE,
    POWER_PROFILE_STRING: POWER_PROFILE,
    SPEED_PROFILE_STRING: SPEED_PROFILE,
    CADENCE_PROFILE_STRING: CADENCE_PROFILE,
    SPEED_CADENCE_PROFILE_STRING: SPEED_CADENCE_PROFILE
}


# DATA PAGE CONSTANTS
TRAINER_TORQUE_DATA_STRING = "Trainer Torque Data"
TRAINER_TORQUE_DATA = fitness_equipment_profile.TRAINER_TORQUE_DATA

GENERAL_FE_DATA_STRING = "General FE Data"
GENERAL_FE_DATA = fitness_equipment_profile.GENERAL_FE_DATA

TRAINER_BIKE_DATA_STRING = "Trainer Bike Data"
TRAINER_BIKE_DATA = fitness_equipment_profile.TRAINER_BIKE_DATA

STANDARD_POWER_DATA_STRING = "Standard Power Data"
STANDARD_POWER_DATA = power_profile.STANDARD_POWER_DATA

WHEEL_TORQUE_DATA_STRING = "Wheel Torque Data"
WHEEL_TORQUE_DATA = power_profile.WHEEL_TORQUE_DATA

SPEED_DEFAULT_DATA_STRING = "Default Data (Speed)"
SPEED_DEFAULT_DATA = speed_profile.DEFAULT_DATA

CADENCE_DEFAULT_DATA_STRING = "Default Data (Cadence)"
CADENCE_DEFAULT_DATA = cadence_profile.DEFAULT_DATA

SC_DEFAULT_DATA_STRING = "Default Data (Speed and Cadence)"
SC_DEFAULT_DATA = speed_cadence_profile.DEFAULT_DATA

HR_DEFAULT_DATA_STRING = "Default Data (Heart Rate)"
HR_DEFAULT_DATA = heartrate_profile.DEFAULT_DATA

DataPageName2Number = {
    TRAINER_TORQUE_DATA_STRING: TRAINER_TORQUE_DATA,
    GENERAL_FE_DATA_STRING: GENERAL_FE_DATA,
    TRAINER_BIKE_DATA_STRING: TRAINER_BIKE_DATA,
    STANDARD_POWER_DATA_STRING: STANDARD_POWER_DATA,
    WHEEL_TORQUE_DATA_STRING: WHEEL_TORQUE_DATA,
    SPEED_DEFAULT_DATA_STRING: SPEED_DEFAULT_DATA,
    CADENCE_DEFAULT_DATA_STRING: CADENCE_DEFAULT_DATA,
    SC_DEFAULT_DATA_STRING: SC_DEFAULT_DATA,
    HR_DEFAULT_DATA_STRING: HR_DEFAULT_DATA
}


# PAGE MEASUREMENT CONSTANTS
PEDAL_POWER_MEASUREMENT = "Pedal Power (%)"
INSTANTANEOUS_POWER_MEASUREMENT = "Instantaneous Power (W)"
AVERAGE_POWER_MEASUREMENT = "Average Power (W)"
AVERAGE_TORQUE_MEASUREMENT = "Average Torque (Nm)"

INSTANTANEOUS_CADENCE_MEASUREMENT = "Instantaneous Cadence (rpm)"
AVERAGE_CADENCE_MEASUREMENT = "Average Cadence (rpm)"

INSTANTANEOUS_SPEED_MEASUREMENT = "Instantaneous Speed (m/s)"
AVERAGE_SPEED_MEASUREMENT = "Average Speed (m/s)"

DISTANCE_TRAVELED_MEASUREMENT = "Distance Traveled (m)"

ELAPSED_TIME_MEASUREMENT = "Elapsed Time (s)"

HEART_RATE_MEASUREMENT = "Heart Rate (bpm)"

pageMeasurementUnits = {
    PEDAL_POWER_MEASUREMENT: '%',
    INSTANTANEOUS_POWER_MEASUREMENT: 'W',
    AVERAGE_POWER_MEASUREMENT: 'W',
    AVERAGE_TORQUE_MEASUREMENT: 'Nm',
    INSTANTANEOUS_CADENCE_MEASUREMENT: 'rpm',
    AVERAGE_CADENCE_MEASUREMENT: 'rpm',
    INSTANTANEOUS_SPEED_MEASUREMENT: 'm/s',
    AVERAGE_SPEED_MEASUREMENT: 'm/s',
    DISTANCE_TRAVELED_MEASUREMENT: 'm',
    ELAPSED_TIME_MEASUREMENT: 's',
    HEART_RATE_MEASUREMENT: 'bpm',
    }

pageMeasurementBounds = {
    PEDAL_POWER_MEASUREMENT: [0, 100],
    INSTANTANEOUS_POWER_MEASUREMENT: [0, 500],
    AVERAGE_POWER_MEASUREMENT: [0, 500],
    AVERAGE_TORQUE_MEASUREMENT: [0, 500],
    INSTANTANEOUS_CADENCE_MEASUREMENT: [0, 200],
    AVERAGE_CADENCE_MEASUREMENT: [0, 200],
    INSTANTANEOUS_SPEED_MEASUREMENT: [0, 30],
    AVERAGE_SPEED_MEASUREMENT: [0, 30],
    DISTANCE_TRAVELED_MEASUREMENT: [0, 9999],
    ELAPSED_TIME_MEASUREMENT: [0, 9999],
    HEART_RATE_MEASUREMENT: [0, 200]
    }
